module.exports = {
  INVALID_EMAIL: "Invalid Email Address",
  PASSWORD_TOO_SHORT: "Password must be at least 8 character",
  USER_SIGNUP: "User signUp successfully",
  USER_SIGNUP_ERROR: "Please check the credential",
  SERVER_ERROR: "Server Error",
  ORDER_PLACED_SUCCESSFULL: "Order placed successfullt",
  INVALID_PASSWORD: "Please enter the valid password",
  INVALID_TOKEN: "Please enter the valid token",
  EMAIL_ALREADY_EXIST: "Email address is already exist",
  USER_SIGNIN: "User signIn successfully",
  TABEL_CREATED_ERROR: "Tabel createation failed",
  TABEL_CREATED: "Tabel created succesfully",
  ORDER_ID: "Your order id created",
  ORDER_PLACED_SUCCESSFULLY: "Your Order placed successfully",
  ORDER_DETAIL_UPDATED: "Your order updated successfully",
  PLEASE_ENTER_THE_MISSING_VALUE: "Please enter the missing value",
  PRODUCT_SAVED: "Product hase been saved",
  PRODUCT_UPDATED: "Product Updated successfully",
  PRODUCT_ID_NOT_FOUND: "Product not fount",
  PRODUCT_OUT_OF_STOCK: "Product out of order",
  PRODUCT_INV_INC: "Product Inventory Increse By 1",
  PRODUCT_INV_DEC: "Product Inventory Decrese By 1",
  MISSING_STATMENT: "Input Parameter Missing",
  INVENTORY_UPDATED: "Inventory Updated Success ",
  PRODUCT_DELETED  : "Product Is delted"
};
